name: Node CI

on: [push, pull_request]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'

    - name: Versions
      run: |
        node --version
        python --version
        ruby --version

    - name: Install
      run: npm install

    - name: Test
      run: npm test
