name: Node CI

on: [push, pull_request]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Use Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Use Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'
    - name: npm install & test
      run: |
        npm install
        npm test
#   codecov:
#     name: codecov
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#     - name: Run codecov
#       run: codecov
